---
dependencies: []
galaxy_info:
  role_name: user
  author: a14m
  description: "Configure user and sudo"
  company: "kartoffeln.work GmbH."
  license: "license MIT"
  min_ansible_version: "2.18"
  platforms:
    - name: ArchLinux
      versions:
        - all
